#!/usr/bin/env python3
"""Build one Hepingjie PDF-background lesson plan."""
from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parents[1]
BACKGROUND = ROOT / "templates/lessonplan/hepingjie_blank.pdf"
BUILD_ROOT = ROOT / "build/lessonplans"
DIST_ROOT = ROOT / "dist/lessonplans"


def lesson_type_label(value: str) -> str:
    mapping = {"new_lesson": "新授课", "review": "复习课", "practice": "练习课"}
    return mapping.get(value, value or "")


def latex_items(items: list[str]) -> str:
    return "\\LPItems{" + "".join(f"\\item {item}\n" for item in items) + "}"


def inline_list(items: list[str]) -> str:
    return "；".join(items)


def blackboard_tex(data: dict) -> str:
    title = data.get("title", "")
    sections = data.get("sections", [])
    lines = [f"\\textbf{{{title}}}" if title else ""]
    lines.extend(f"{idx}. {item}" for idx, item in enumerate(sections, 1))
    return "\\par ".join(line for line in lines if line)


def process_rows(entries: list[dict]) -> str:
    rows = []
    for entry in entries:
        teacher = latex_items(entry["teacher"])
        student = latex_items(entry["student"])
        rows.append(
            "\\LPProcessRow"
            f"{{{entry['stage']}}}"
            f"{{{teacher}}}"
            f"{{{student}}}"
            f"{{{entry['minutes']}}}"
        )
    return "\n".join(rows)


def page_process(data: dict, page: int) -> list[dict]:
    return [entry for entry in data["process"] if entry.get("page") == page]


def render_tex(data: dict) -> str:
    meta = data["meta"]
    date = meta.get("teaching_date") or {}
    page2 = process_rows(page_process(data, 2))
    page3 = process_rows(page_process(data, 3))
    page4 = process_rows(page_process(data, 4))
    return rf"""% !TeX program = xelatex
% Generated by scripts/build_lessonplan.py. Do not edit build output by hand.
\documentclass[UTF8,a4paper,zihao=-4,fontset=windows]{{ctexart}}
\input{{tex/lessonplan/hepingjie_render.tex}}

\begin{{document}}

\LPBackgroundPage{{1}}{{
  \LPCenterBox{{\LPDateYearX}}{{\LPDateY}}{{12mm}}{{5mm}}{{{date.get('year', '')}}}
  \LPCenterBox{{\LPDateMonthX}}{{\LPDateY}}{{10mm}}{{5mm}}{{{date.get('month', '')}}}
  \LPCenterBox{{\LPDateDayX}}{{\LPDateY}}{{10mm}}{{5mm}}{{{date.get('day', '')}}}
  \LPCenterBox{{\LPRecordPageX}}{{\LPRecordPageY}}{{10mm}}{{5mm}}{{{meta.get('page_no', '')}}}
  \LPTextBox{{\LPTopicX}}{{\LPTopicY}}{{\LPTopicW}}{{8mm}}{{{meta['title']}}}
  \LPTextBox{{\LPTypeX}}{{\LPTypeY}}{{\LPTypeW}}{{8mm}}{{{lesson_type_label(meta.get('lesson_type', ''))}}}
  \LPCenterBox{{\LPUnitTotalX}}{{\LPUnitTotalY}}{{12mm}}{{5mm}}{{{meta.get('unit_total_periods', '')}}}
  \LPCenterBox{{\LPTopicTotalX}}{{\LPTopicTotalY}}{{12mm}}{{5mm}}{{{meta.get('topic_total_periods', '')}}}
  \LPCenterBox{{\LPCurrentPeriodX}}{{\LPCurrentPeriodY}}{{12mm}}{{5mm}}{{{meta.get('current_period', '')}}}
  \LPTextBox{{\LPBodyX}}{{\LPObjectiveY}}{{\LPBodyW}}{{\LPObjectiveH}}{{{latex_items(data['objectives'])}}}
  \LPTextBox{{\LPBodyX}}{{\LPKeyPointY}}{{\LPBodyW}}{{\LPKeyPointH}}{{{inline_list(data['key_points'])}}}
  \LPTextBox{{\LPBodyX}}{{\LPDifficultyY}}{{\LPBodyW}}{{\LPDifficultyH}}{{{inline_list(data['difficulties'])}}}
  \LPTextBox{{\LPBodyX}}{{\LPMethodY}}{{\LPBodyW}}{{\LPMethodH}}{{{inline_list(data['methods'])}}}
  \LPTextBox{{\LPBodyX}}{{\LPMediaY}}{{\LPBodyW}}{{\LPMediaH}}{{{inline_list(data['media'])}}}
  \LPTextBox{{\LPBodyX}}{{\LPBlackboardY}}{{\LPBodyW}}{{\LPBlackboardH}}{{{blackboard_tex(data['blackboard'])}}}
}}

\LPBackgroundPage{{2}}{{
  \LPProcessBox{{\LPProcessX}}{{\LPProcessY}}{{\LPProcessW}}{{\LPProcessFullH}}{{{page2}}}
}}

\LPBackgroundPage{{3}}{{
  \LPProcessBox{{\LPProcessX}}{{\LPProcessY}}{{\LPProcessW}}{{\LPProcessFullH}}{{{page3}}}
}}

\LPBackgroundPage{{4}}{{
  \LPProcessBox{{\LPProcessX}}{{\LPProcessY}}{{\LPProcessW}}{{\LPProcessPageFourH}}{{{page4}}}
}}

\end{{document}}
"""


def compile_tex(tex_file: Path, output_dir: Path) -> tuple[Path, float, Path]:
    xelatex = shutil.which("xelatex")
    if not xelatex:
        raise RuntimeError("xelatex was not found")
    output_dir.mkdir(parents=True, exist_ok=True)
    env = os.environ.copy()
    env["TEXINPUTS"] = ".//" + os.pathsep + "tex//" + os.pathsep + env.get("TEXINPUTS", "")
    rel_tex = tex_file.resolve().relative_to(ROOT.resolve()).as_posix()
    rel_out = output_dir.resolve().relative_to(ROOT.resolve()).as_posix()
    cmd = [
        xelatex,
        "-interaction=nonstopmode",
        "-halt-on-error",
        f"-output-directory={rel_out}",
        rel_tex,
    ]
    started = time.perf_counter()
    output_parts = []
    code = 0
    for _ in range(2):
        result = subprocess.run(
            cmd,
            cwd=ROOT,
            env=env,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            encoding="utf-8",
            errors="replace",
        )
        output_parts.append(result.stdout)
        code = result.returncode
        if code != 0:
            break
    seconds = time.perf_counter() - started
    log = output_dir / "lessonplan.compile.log"
    log.write_text("\n".join(output_parts), encoding="utf-8")
    pdf = output_dir / "lessonplan.pdf"
    if code != 0:
        raise RuntimeError(f"xelatex failed for {tex_file}; see {log}")
    if not pdf.exists():
        raise RuntimeError(f"expected PDF was not generated: {pdf}")
    return pdf, seconds, log


def build(lesson_id: str) -> dict:
    source = ROOT / "lessons" / lesson_id / "lessonplan.yml"
    if not source.exists():
        raise FileNotFoundError(source)
    if not BACKGROUND.exists():
        raise FileNotFoundError(BACKGROUND)

    data = yaml.safe_load(source.read_text(encoding="utf-8"))
    build_dir = BUILD_ROOT / lesson_id
    build_dir.mkdir(parents=True, exist_ok=True)
    copied_yml = build_dir / "lessonplan.yml"
    copied_yml.write_text(source.read_text(encoding="utf-8"), encoding="utf-8")
    tex_file = build_dir / "lessonplan.tex"
    tex_file.write_text(render_tex(data), encoding="utf-8")
    pdf, seconds, log = compile_tex(tex_file, build_dir)

    title = data["meta"]["title"]
    dist_pdf = DIST_ROOT / f"{lesson_id}_{title}_教案.pdf"
    DIST_ROOT.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(pdf, dist_pdf)
    return {
        "lesson_id": lesson_id,
        "title": title,
        "build_pdf": str(pdf.relative_to(ROOT)),
        "dist_pdf": str(dist_pdf.relative_to(ROOT)),
        "compile_seconds": round(seconds, 2),
        "log": str(log.relative_to(ROOT)),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("lesson_id")
    args = parser.parse_args()
    try:
        result = build(args.lesson_id)
    except Exception as exc:
        print(f"[FAIL] {exc}", file=sys.stderr)
        raise
    print(f"[OK] {result['lesson_id']} -> {result['dist_pdf']} ({result['compile_seconds']}s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
